### ISSUE TITLE
What does the IORef Algebra instance look like with the changes to master?

### ISSUE THREAD

**Issue by Avi-D-coder** [fused-effects/fused-effects-exceptions#13]
I'm trying to write a simple atomic `IORef` counter with the unreleased fused-effects master, so I'm wondering what `StateC` instance looks like without `handleCoercible`, etc..

**Comment by robrix** [comment]
I did this in my game Starlight: https://github.com/robrix/starlight/blob/master/src/Control/Carrier/State/IORef.hs#L46-L50

**Comment by Avi-D-coder** [comment]
Thanks
