### ISSUE TITLE
Swap catch/catchSync?

### ISSUE THREAD

**Issue by mitchellwrosen** [fused-effects/fused-effects-exceptions#3]
In both `safe-exceptions` and `unliftio`, the function called `catch` only catches synchronous exceptions. In my experience this is always the behavior I want (as there exist `finally`, `onException`, `bracket`, etc. for performing cleanup in case anything goes wrong, including getting hit with an async exception).

What do you think about swapping the names here to `catch` and `catchAsync`?

**Comment by patrickt** [comment]
I wouldn’t object, given that `safe-exceptions` sets this precedent.
